### ISSUE TITLE
Missing Packages and ProjectSettings directories

### ISSUE THREAD

**Issue by andybak** [CJT-Jackton/Crystal-Caustics#2]
Might be the reason it's not working for me.

What Unity and HDRP versions is this meant to be using? (adding packages and project settings would actually answer this question in itself)

**Comment by CJT-Jackton** [comment]
Packages and ProjectSettings directories added. So looks like this project is using HDRP 5.7.2.

Well, this project is done back in the time that I basically know nothing about Unity therefore I have no idea what I'm doing and which part should be included. I will looking into upgrade it to use a newer and stabler HDRP when I have some free time.
